mod test_allocator;
mod test_panic;
mod test_pmm;
mod test_syscall;
mod test_task;
mod test_tss;
mod test_vfs;
mod test_vmm;

pub fn run_tests() {
    test_allocator::test_vec_allocation();
    test_allocator::test_box_allocation();
    test_allocator::test_string_allocation();
    test_allocator::test_multiple_allocations();
    test_panic::test_panic_constants();
    test_panic::test_serial_hex_output();
    test_pmm::test_pmm_initialized();
    test_pmm::test_pmm_allocate_single_page();
    test_pmm::test_pmm_allocate_multiple_pages();
    test_pmm::test_pmm_stress();
    test_vmm::test_page_fault_handler();
    test_syscall::test_syscall_table_initialized();
    test_syscall::test_syscall_numbers();
    test_syscall::test_system_ticks();
    test_syscall::test_syscall_handler_exists();
    test_syscall::test_file_descriptor_enum();
    test_syscall::test_errno_enum();
    test_syscall::test_syscall_number_from_u32();
    test_task::test_task_creation();
    test_task::test_scheduler_init();
    test_task::test_task_spawn();
    test_task::test_task_state_transitions();
    test_task::test_task_is_runnable();
    test_task::test_id_allocator_basic();
    test_task::test_id_allocator_reuse();
    test_task::test_id_allocator_max();
    test_task::test_scheduler_tick();
    test_task::test_scheduler_tick_time_slice();
    test_task::test_scheduler_preemptive_tick();
    test_tss::test_tss_initialized();
    test_tss::test_tss_double_fault_stack();
    test_tss::test_gdt_has_code_segment();
    test_tss::test_tss_ist_index();
    test_vfs::test_vfs_inode_creation();
    test_vfs::test_vfs_directory_inode();
    test_vfs::test_vfs_inode_mkdir();
    test_vfs::test_vfs_inode_create_file();
    test_vfs::test_vfs_inode_read_write();
    test_vfs::test_vfs_inode_unlink();
    test_vfs::test_vfs_inode_rmdir();
    test_vfs::test_vfs_file_table();
    test_vfs::test_vfs_file_read_write();
    test_vfs::test_vfs_mount_namespace();
    test_vfs::test_vfs_dentry();
    test_vfs::test_vfs_dentry_lookup();
    test_vfs::test_vfs_super_block();
    test_vfs::test_vfs_symlink();
    test_vfs::test_vfs_readlink();
    test_vfs::test_vfs_file_seek();
    test_vfs::test_vfs_file_truncate();
    test_vfs::test_vfs_file_dup();
    test_vfs::test_vfs_readdir();
    test_vfs::test_vfs_mount_unmount();
    test_vfs::test_vfs_walk_path();
    test_vfs::test_initramfs_root_creation();
    test_vfs::test_initramfs_children();
    test_vfs::test_initramfs_file_read();
    test_vfs::test_initramfs_readdir();
    test_vfs::test_tmpfs_root_creation();
    test_vfs::test_tmpfs_children();
    test_vfs::test_tmpfs_mkdir();
    test_vfs::test_tmpfs_create_file();
    test_vfs::test_tmpfs_read_write();
    test_vfs::test_tmpfs_unlink();
    test_vfs::test_tmpfs_rmdir();
    test_vfs::test_tmpfs_readdir();
    test_vfs::test_tmpfs_truncate();
    test_vfs::test_tmpfs_symlink();
    test_vfs::test_tmpfs_readlink();
}
